name: "Feature request"
description: "Tell us about function you want to see in chroot-distro"
title: "[Feature]: "
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              This is a feature tracker of the Chroot Distro - a helper script for chroot to manage distribution installations. Please use it accordingly to selected ticket type.

              It is not guaranteed that a specific requested feature will be implemented. However, we will try to consider all reasonable requests.
    - type: textarea
      attributes:
          label: Feature description
          description: |
              A clear and concise description of a feature you would like to see in chroot-distro.
      validations:
          required: true
